status = [
	"CI",
]
pr_status = [
	"CI-PR", "Lint",
]
timeout_sec = 7200
prerun_timeout_sec = 7200
delete_merged_branches = true
cut_body_after = ""
block_labels = ["M: blocked", "M: require changes"]
