base_url = "https://clap.rs"

title = "Clap"
description = "Fast & Modern CLI Framework for Rust"

build_search_index = true

default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

external_links_target_blank = true
