blank_issues_enabled: true
contact_links:
  - name: Ask a question
    about: You've come to seek help or want to discuss something related to clap
    url: https://github.com/clap-rs/clap/discussions/new
    # TODO: Question template (waiting for discussions template feature)
